[[redirects]]
  from = "/api/*"
  to = "https://primalsheetsapi.jaydeedev.workers.dev/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    X-Forwarded-Host = "https://primalsheets.netlify.app/"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/_shell.html"
  status = 200